name: 'Develop'
on:
  pull_request:
    types:
      - closed
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('shadow-cljs.edn') }}
      - run: yarn
      - run: yarn release
      - name: wrike-ist
        env:
          WRIKE_TOKEN: ${{ secrets.WRIKE_TOKEN }}
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        uses: ./
        with:
          opened: "In review"
