name: 'Build-less test'
on:
  push:
    branches:
      - main
      - ayush/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: wrike-ist
        env:
          WRIKE_TOKEN: ${{ secrets.WRIKE_TOKEN }}
        uses: ./
        with:
          opened: "In review"
